Ordered list
learnhouse/learnhouse pull request #110
Opened 2023-08-21 19:36 UTC by ksanjeev284

Hi, I have added the Ordered List function; please review it.

2023-08-23 15:50 UTC, swve requested changes

2023-08-23 15:50 UTC, swve commented on config/config.yaml
> -  development_mode: false
You pushed config changes, I believe this is an error.

2023-08-23 15:53 UTC, swve reviewed
You also need to add the extension in the DynamicCanva here : https://github.com/learnhouse/learnhouse/tree/c1f9cda15cceef48ef1e7601dc35cb0a1a8f4d5d/front/components/Pages/Activities/DynamicCanva

2023-08-23 16:03 UTC, swve commented
Also, can you rebase with the current `dev` branch, thanks!

2023-08-23 19:37 UTC, ksanjeev284 reviewed
Hi,

I have fixed all issues, please check

2023-08-24 09:23 UTC, merged

2023-08-24 09:23 UTC, swve commented
Thanks @ksanjeev284 for your contribution! 
It is merged 🎉