Migrated Langchain
learnhouse/learnhouse pull request #376
Opened 2024-10-27 11:20 UTC by prateek-1803

Migrated to langchain version v0.2.

2024-10-27 19:08 UTC, swve requested changes
Hello @prateek-1803, thanks for your contributions here is my review : 

- Please update the poetry and lock files to accommodate the changes you made on the code. 
- Remove unnecessary lines that I quoted

2024-10-28 06:35 UTC, prateek-1803 commented
@swve Updated the PR

2024-10-30 22:38 UTC, swve approved these changes
LGTM! 

Thanks for your contribution @prateek-1803

2024-10-30 22:38 UTC, swve commented on apps/api/src/services/ai/base.py
> +    pass
```suggestion
```

2024-10-30 22:39 UTC, merged