Added toast notifications
learnhouse/learnhouse pull request #416
Opened 2024-12-18 16:50 UTC by jey-exp

Successful merging of this PR will close #181 

Implemented toast in user actions where necessary.

2024-12-18 17:59 UTC, jey-exp commented
@swve Build fails due to parameter token.

Sorry I couldn't fix it, can you help me fixing it please.

2025-01-25 12:09 UTC, swve requested changes
Hey @jey-exp, thanks for your contributions

I think it's better to not have the toasts be executed from the services and instead from the UI itself (React), additionally there is some conflicts with the main branch

I'll be merging once these issues fixed

Thanks

2025-01-29 12:56 UTC, jey-exp commented
>I think it's better to not have the toasts be executed from the services and instead from the UI itself (React), additionally there is some conflicts with the main branch

Okay, I will look into it

Thanks

2025-03-05 19:15 UTC, jey-exp commented
@swve made some changes

2025-03-06 09:09 UTC, swve commented
Awesome @jey-exp, thanks for your contribution 🙏

2025-03-06 09:09 UTC, merged